# Generated by Django 6.0.3 on 2026-04-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/receipts/'),
        ),
    ]
