# Generated by Django 6.0.4 on 2026-04-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pro_member',
            field=models.BooleanField(default=True),
        ),
    ]
