# Generated by Django 6.0.4 on 2026-04-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_journalentry_ledgeraccount_journalitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societymaintenancesettings',
            name='late_fee_percentage',
        ),
        migrations.AddField(
            model_name='societymaintenancesettings',
            name='late_fee_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount to charge if paid after due date', max_digits=10),
        ),
    ]
