# Generated by Django 6.0.4 on 2026-04-19 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_societymaintenancesettings_late_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='months_paid',
            field=models.PositiveIntegerField(default=1, help_text='Number of months paid in advance'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
