# Generated by Django 6.0.4 on 2026-04-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0004_remove_bill_parking_charge_remove_bill_water_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='months_covered',
            field=models.PositiveIntegerField(default=1, help_text='Number of months this bill covers'),
        ),
    ]
