from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.template.loader import get_template
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from io import BytesIO
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, get_user_model
from django.urls import reverse
from django.db import IntegrityError
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from decimal import Decimal
from datetime import date, datetime
import re, os
from django.conf import settings
from django.utils import timezone
from django.db.models import Sum
from resident.models import Bill
from PIL import Image
import google.generativeai as genai
import json

def add_pdf_watermark(canvas, doc):
    """Draws a light watermark in the center of the PDF page."""
    from django.contrib.staticfiles import finders
    canvas.saveState()
    try:
        # Use finders to get the correct path in production/Vercel
        img_path = finders.find('core/pwa/TheManager.jpeg')
        if img_path:
            canvas.setFillAlpha(0.15)  # Slightly darker for better visibility
            w, h = doc.pagesize
            # Center the logo (7cm x 7cm)
            canvas.drawImage(img_path, w/2 - 3.5*cm, h/2 - 3.5*cm, width=7*cm, height=7*cm, mask='auto', preserveAspectRatio=True)
    except Exception as e:
        print(f"Watermark rendering error: {e}")
    canvas.restoreState()

User = get_user_model()

@never_cache
@csrf_protect
def register(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        full_name = request.POST.get('full_name', '')
        password = request.POST.get('password')
        role = request.POST.get('role', 'resident')
        mobile = request.POST.get('mobile')
        unit_number = request.POST.get('unit_number', '')

        if role in ['secretary', 'resident']:
            invite_code = request.POST.get('invite_code')
            if not invite_code:
                messages.error(request, 'Invite code is required.')
                return render(request, 'core/register.html')

            from .models import InviteCode
            invite_obj = InviteCode.objects.filter(code=invite_code).first()
            if not invite_obj:
                messages.error(request, 'Invalid invite code.')
                return render(request, 'core/register.html')

            society = invite_obj.society_name

            if role == 'secretary':
                existing_secretary = User.objects.filter(role='secretary', society_name=society).exists()
                if existing_secretary:
                    messages.error(request, 'A secretary already exists for this society.')
                    return render(request, 'core/register.html')
        else:
            society = None

        try:
            user = User.objects.create_user(
                username=email,
                email=email,
                first_name=full_name,
                password=password,
                role=role,
                # All residents who register publicly are owners by default.
                # Rental profiles are created by owners from within their portal.
                resident_role='owner' if role == 'resident' else None,
                mobile_number=mobile,
                society_name=society,
                unit_number=unit_number,
            )
            return redirect(reverse('login') + '?registered=true')
        except IntegrityError:
            messages.error(request, 'An account with this email already exists.')
            return render(request, 'core/register.html')
    return render(request, 'core/register.html')

@login_required
def dashboard_redirect(request):
    if request.user.role == 'company':
        return redirect('company_dashboard')
    if request.user.role == 'admin' or request.user.role == 'secretary':
        return redirect('admin_dashboard')
    if request.user.role == 'watchman':
        return redirect('watchman_dashboard')
    return redirect('resident_dashboard')

@login_required
def placeholder_view(request, feature_name):
    if feature_name.lower() == "notices":
        return redirect('notices')
    return render(request, 'core/placeholder.html', {'feature_name': feature_name.capitalize()})

@login_required
def profile_view(request):
    return render(request, 'core/profile.html')

@login_required
def members_view(request):
    if request.user.role == 'company':
        # Get all invite codes generated by this company to list active societies
        from .models import InviteCode
        invite_codes = InviteCode.objects.filter(company=request.user)
        # Unique societies
        # Since each society gets 1 code, the invite_codes queryset IS the list of societies.
        return render(request, 'core/company_members.html', {'societies': invite_codes})
    
    else:
        # Residents and Secretaries see members of their own society
        society_name = request.user.society_name
        members = User.objects.filter(society_name=society_name).exclude(id=request.user.id)
        
        # Calculate pending amounts for each member
        from resident.models import Bill
        from decimal import Decimal
        from datetime import date
        today = date.today()
        
        for member in members:
            pending_bills = member.bills.filter(status='Pending')
            total = Decimal('0.00')
            for bill in pending_bills:
                # Dynamic late fee check (same as other views)
                if bill.due_date and today > bill.due_date:
                    if not bill.is_late_applied:
                        late_fee = bill.total_amount * Decimal('0.21')
                        bill.late_fee_amount = late_fee
                        bill.total_amount += late_fee
                        bill.is_late_applied = True
                        bill.save()
                total += bill.total_amount
            member.pending_amount = total
            member.pending_count = pending_bills.count()
        
        from .models import InviteCode
        invite_obj = InviteCode.objects.filter(society_name=society_name).first()
        invite_code = invite_obj.code if invite_obj else None
        
        return render(request, 'core/society_members.html', {
            'members': members, 
            'society_name': society_name,
            'invite_code': invite_code
        })

@login_required
def notices_view(request):
    from .models import Notice
    society_name = request.user.society_name
    notices = Notice.objects.filter(society_name=society_name).order_by('-created_at')
    return render(request, 'core/notices.html', {'notices': notices})

def extract_ocr_details(image_file):
    """Helper to extract details using Google Gemini Flash (Vision)."""
    api_key = os.environ.get('GEMINI_API_KEY')
    
    if not api_key:
        print("CRITICAL: GEMINI_API_KEY missing from environment.")
        return {}

    # Reset file pointer
    image_file.seek(0)
    image_bytes = image_file.read()
    image_file.seek(0)
    
    try:
        from google.generativeai.types import HarmCategory, HarmBlockThreshold
        import google.generativeai as genai
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-1.5-flash')
        
        # Prepare image and resize if needed to speed up / avoid limits
        img = Image.open(BytesIO(image_bytes))
        if img.width > 1200:
            ratio = 1200 / float(img.width)
            new_height = int(float(img.height) * ratio)
            img = img.resize((1200, new_height), Image.Resampling.LANCZOS)
        
        prompt = """
        ACT AS AN OCR SPECIALIST. Analyze this Indian UPI payment receipt (GPay, PhonePe, Paytm).
        Locate:
        1. Total Amount Paid.
        2. Date of transaction.
        3. Transaction ID / UTR / UPI Ref No.
        4. The last 4 digits of the account number used/mentioned.
        
        Return EXACTLY this JSON format and nothing else:
        {
          "amount": float,
          "date": "DD/MM/YYYY",
          "txn_id": "string",
          "acc_digits": "string"
        }
        
        If not found, use null. Be very precise.
        """
        
        # Permissive safety settings for PII receipts
        safety_settings = [
            {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"},
        ]
        
        response = model.generate_content([prompt, img], safety_settings=safety_settings)
        
        # Check if we got a valid response (not blocked by safety filters)
        if not response.candidates:
            print(f"DEBUG AI: No candidates returned.")
            return {'error': 'No response from AI'}
            
        if not response.candidates[0].content.parts:
            reason = response.candidates[0].finish_reason
            print(f"DEBUG AI: Blocked response. Reason: {reason}")
            return {'error': f'AI Blocked: {reason}'}

        clean_resp = response.text.replace('```json', '').replace('```', '').strip()
        
        # Locate JSON content within potential text
        match = re.search(r'\{.*\}', clean_resp, re.DOTALL)
        if match:
            data = json.loads(match.group(0))
        else:
            data = {}
            
        return {
            'amount': data.get('amount'),
            'date': data.get('date'),
            'txn_id': data.get('txn_id'),
            'acc_digits': data.get('acc_digits')
        }
    except Exception as e:
        print(f"Gemini API Error: {e}")
        return {}

@login_required
@csrf_protect
def process_ocr_preview(request):
    """AJAX endpoint for OCR preview."""
    if request.method != 'POST':
        return JsonResponse({'success': False}, status=405)
    
    image_file = request.FILES.get('proof_image')
    if not image_file:
        return JsonResponse({'success': False}, status=400)

    try:
        details = extract_ocr_details(image_file)
        if 'error' in details:
            return JsonResponse({'success': False, 'error': details['error']}, status=200)
            
        return JsonResponse({
            'success': True,
            'amount': details.get('amount'),
            'date': details.get('date'),
            'txn_id': details.get('txn_id'),
            'acc_digits': details.get('acc_digits')
        })
    except Exception as e:
        return JsonResponse({'success': False, 'error': str(e)}, status=500)

@login_required
def maintenance_view(request):
    from .models import InviteCode, PaymentProof, RentPaymentProof, SocietyMaintenanceSettings, RentalChargeSettings
    from django.utils import timezone
    from datetime import datetime
    
    is_rental = (request.user.role == 'resident' and request.user.resident_role == 'rental')
    society_name = request.user.society_name
    
    # Context Logic
    if is_rental:
        rental_charge = RentalChargeSettings.objects.filter(rental_user=request.user).first()
        target_fee = rental_charge.monthly_rent if rental_charge else Decimal('0.00')
        proofs = RentPaymentProof.objects.filter(rental_user=request.user).order_by('-created_at')
        settings_obj = rental_charge
    else:
        maintenance_settings = SocietyMaintenanceSettings.objects.filter(society_name=society_name).first()
        target_fee = request.user.get_maintenance_balance()
        proofs = (PaymentProof.objects.filter(society_name=society_name) if request.user.role == 'secretary' 
                  else PaymentProof.objects.filter(user=request.user)).order_by('-created_at')
        settings_obj = maintenance_settings

    if request.method == 'POST' and request.FILES.get('proof_image'):
        proof_file = request.FILES.get('proof_image')
        amount_raw = request.POST.get('amount')
        date_str = request.POST.get('date')
        txn_id = request.POST.get('txn_id')
        acc_digits = request.POST.get('account_digits')
        
        # 1. Unique Transaction ID Check
        if PaymentProof.objects.filter(transaction_id=txn_id).exists() or RentPaymentProof.objects.filter(transaction_id=txn_id).exists():
            messages.error(request, f"Failure: Transaction ID '{txn_id}' has already been used.")
            return redirect('maintenance')

        if is_rental:
            proof = RentPaymentProof.objects.create(rental_user=request.user, owner=request.user.owner, proof_image=proof_file)
        else:
            eff_society = society_name or (request.user.owner.society_name if hasattr(request.user, 'owner') and request.user.owner else "Global")
            proof = PaymentProof.objects.create(user=request.user, society_name=eff_society, proof_image=proof_file)
            
        # Parse Amount
        clean_amount = ''.join(c for c in str(amount_raw) if c.isdigit() or c == '.')
        amt_paid = Decimal(clean_amount) if clean_amount else Decimal('0.00')
        proof.extracted_amount = amt_paid
        proof.transaction_id = txn_id
        proof.extracted_account_digits = acc_digits
        
        # Parse Date
        if date_str:
            try:
                proof.extracted_date = datetime.strptime(date_str, "%d/%m/%Y").date()
            except:
                try: proof.extracted_date = datetime.strptime(date_str, "%Y-%m-%d").date()
                except: pass
        
        # Verification Logic
        # User requested: Compare amount, account digits (from secretary settings), and subtract from fees
        expected_acc = settings_obj.expected_payee_account if not is_rental and settings_obj else None
        
        # Auto-verify if conditions met, otherwise it still subtracts if we set to 'verified'
        # To "subtract from fees", the proof MUST be in 'verified' or 'approved' state
        proof.status = 'verified'
        
        # If account digits provided but don't match, we could flag it, 
        # but the request says "if it doesn't match just subtract", so we verify it anyway.
        
        proof.save()
        messages.success(request, f"Success: ₹{amt_paid} has been recorded and subtracted from your outstanding balance.")
        return redirect('maintenance')

    return render(request, 'core/maintenance.html', {
        'proofs': proofs,
        'target_fee': target_fee,
        'settings': settings_obj,
        'is_rental': is_rental
    })

@login_required
def verify_payment_proof(request, proof_id, action):
    """Allows a Secretary, Admin, or Owner to manually approve or reject a payment proof."""
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    
    from .models import PaymentProof, RentPaymentProof
    
    # 1. Try to find as a Maintenance Proof (Secretary/Admin)
    proof = PaymentProof.objects.filter(id=proof_id).first()
    if proof:
        if request.user.role not in ['secretary', 'admin'] or proof.society_name != request.user.society_name:
            error_msg = "Permission denied for this maintenance proof."
            if is_ajax: return JsonResponse({'success': False, 'message': error_msg}, status=403)
            messages.error(request, error_msg)
            return redirect('maintenance')
    else:
        # 2. Try to find as a Rent Proof (Owner)
        proof = RentPaymentProof.objects.filter(id=proof_id, owner=request.user).first()
        if not proof:
            error_msg = "Proof not found or access denied."
            if is_ajax: return JsonResponse({'success': False, 'message': error_msg}, status=404)
            messages.error(request, error_msg)
            return redirect('maintenance')

    # Status Update Logic
    if action == 'approve':
        proof.status = 'approved'
        messages.success(request, f"Proof #{proof.id} has been manually approved.")
    elif action == 'reject':
        proof.status = 'rejected'
        messages.warning(request, f"Proof #{proof.id} has been rejected.")
    else:
        error_msg = "Invalid action requested."
        if is_ajax: return JsonResponse({'success': False, 'message': error_msg}, status=400)
        messages.error(request, error_msg)
        return redirect('maintenance')
        
    proof.save()
    
    if is_ajax:
        return JsonResponse({
            'success': True, 
            'status': proof.status, 
            'message': f"Proof {action}ed successfully."
        })
        
    return redirect('maintenance')

@login_required
def delete_payment_proof(request, proof_id):
    from .models import PaymentProof, RentPaymentProof
    is_rental = (request.user.role == 'resident' and request.user.resident_role == 'rental')
    
    if is_rental:
        proof = RentPaymentProof.objects.filter(id=proof_id, rental_user=request.user).first()
    else:
        proof = PaymentProof.objects.filter(id=proof_id).first()
    
    if not proof:
        messages.error(request, "Proof not found.")
        return redirect('maintenance')
    
    # Check permission: Only owner or secretary can delete
    # For rent: only tenant or their owner
    can_delete = False
    if is_rental and (proof.rental_user == request.user or proof.owner == request.user):
        can_delete = True
    elif not is_rental and (proof.user == request.user or request.user.role == 'secretary'):
        can_delete = True

    if can_delete:
        proof.delete()
        messages.success(request, "Payment proof deleted successfully.")
    else:
        messages.error(request, "You do not have permission to delete this proof.")
        
    return redirect('maintenance')


@login_required
def generate_proof_receipt_pdf(request, proof_id):
    from .models import PaymentProof

    proof = PaymentProof.objects.filter(id=proof_id, user=request.user).first()

    if not proof:
        messages.error(request, "Receipt not found.")
        return redirect('maintenance')

    if proof.status not in ['verified', 'approved']:
        messages.error(request, "Receipt is only available for verified payments.")
        return redirect('maintenance')

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []
    title_style = ParagraphStyle('title', parent=styles['Title'], fontSize=18,
                                  textColor=colors.HexColor('#1a1a2e'), spaceAfter=6)
    story.append(Paragraph('PAYMENT PROOF RECEIPT', title_style))
    story.append(HRFlowable(width='100%', thickness=1, color=colors.HexColor('#e0e0e0')))
    story.append(Spacer(1, 0.4*cm))
    data = [
        ['Proof ID', f'PR-{proof.id}'],
        ['Resident', proof.user.get_full_name() or proof.user.username],
        ['Society', proof.society_name or '—'],
        ['Date Submitted', str(proof.created_at.date())],
        ['Transaction ID', proof.transaction_id or '—'],
        ['Amount', f'Rs. {proof.extracted_amount}'],
        ['Status', proof.status.upper()],
    ]
    table = Table(data, colWidths=[6*cm, 10*cm])
    table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, colors.HexColor('#f9f9f9')]),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#e0e0e0')),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#e0e0e0')),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(table)
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph('This is a system-generated receipt.', ParagraphStyle(
        'footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey, alignment=TA_CENTER)))
    doc.build(story)
    pdf = buffer.getvalue()
    buffer.close()

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="receipt_proof_{proof.id}.pdf"'
    response.write(pdf)
    return response
@login_required
def generate_proof_receipt(request, proof_id):
    from .models import PaymentProof, RentPaymentProof
    
    # Try to find the proof in either model
    proof = PaymentProof.objects.filter(id=proof_id).first()
    if not proof:
        proof = RentPaymentProof.objects.filter(id=proof_id).first()
        
    if not proof:
        raise Http404("Payment proof not found.")

    # Permission Check
    can_view = False
    u_soc = (request.user.society_name or "").strip().lower()
    
    if request.user.role in ['secretary', 'admin']:
        # Admin/Secretary can view if it belongs to their society
        p_soc = ""
        if hasattr(proof, 'society_name'):
            p_soc = (proof.society_name or "").strip().lower()
        elif hasattr(proof, 'owner'):
            p_soc = (proof.owner.society_name or "").strip().lower()
            
        if p_soc == u_soc and u_soc != "":
            can_view = True
    elif hasattr(proof, 'user') and proof.user == request.user:
        can_view = True
    elif hasattr(proof, 'rental_user') and proof.rental_user == request.user:
        can_view = True
        
    if not can_view:
        messages.error(request, "Permission denied.")
        return redirect('maintenance')

    if proof.status not in ['verified', 'approved']:
        messages.error(request, "Receipt is only available for verified/approved payments.")
        return redirect('maintenance')

    user_for_receipt = getattr(proof, 'user', getattr(proof, 'rental_user', None))

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []
    title_style = ParagraphStyle('title', parent=styles['Title'], fontSize=18,
                                  textColor=colors.HexColor('#1a1a2e'), spaceAfter=6)
    story.append(Paragraph('PAYMENT RECEIPT', title_style))
    story.append(Paragraph(f'Proof #{proof.id}', ParagraphStyle('sub', parent=styles['Normal'],
                                                                  fontSize=10, textColor=colors.black, spaceAfter=12)))
    story.append(HRFlowable(width='100%', thickness=1.5, color=colors.black))
    story.append(Spacer(1, 0.4*cm))
    data = [
        ['Resident', user_for_receipt.get_full_name() or user_for_receipt.username],
        ['Society', user_for_receipt.society_name or '—'],
        ['Unit No.', user_for_receipt.unit_number or '—'],
        ['Month', proof.created_at.strftime('%B %Y')],
        ['Transaction ID', proof.transaction_id or 'SOCIETY_INTERNAL'],
        ['Amount Paid', f'Rs. {proof.extracted_amount or "0.00"}'],
        ['Status', 'Verified'],
        ['Date', str(proof.extracted_date or proof.created_at.date())],
    ]
    table = Table(data, colWidths=[6*cm, 10*cm])
    table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, colors.HexColor('#f2f2f2')]),
        ('BOX', (0, 0), (-1, -1), 1, colors.black),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.black),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(table)
    story.append(Spacer(1, 0.8*cm))
    story.append(HRFlowable(width='100%', thickness=1, color=colors.HexColor('#e0e0e0')))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph('This is a system-generated receipt.', ParagraphStyle(
        'footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey, alignment=TA_CENTER)))
    doc.build(story, onFirstPage=add_pdf_watermark, onLaterPages=add_pdf_watermark)
    pdf = buffer.getvalue()
    buffer.close()

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="receipt_{proof.id}.pdf"'
    response.write(pdf)
    return response



@login_required
def watchman_dashboard(request):
    if request.user.role != 'watchman':
        return redirect('home')
    
    from admin_panel.models import Visitor
    from django.contrib import messages
    
    if request.method == 'POST':
        name = request.POST.get('name')
        unit = request.POST.get('unit')
        vehicle_number = request.POST.get('vehicle_number')
        if vehicle_number:
            vehicle_number = vehicle_number.upper()
        visitor_photo = request.FILES.get('visitor_photo')
        vehicle_photo = request.FILES.get('vehicle_photo')
        watchman_name = request.POST.get('watchman_name', request.user.get_full_name() or request.user.username)
        
        Visitor.objects.create(
            name=name,
            unit=unit,
            vehicle_number=vehicle_number,
            visitor_photo=visitor_photo,
            vehicle_photo=vehicle_photo,
            recorded_by=watchman_name,
            status='Inside'
        )
        messages.success(request, f"Entry recorded for {name} (Unit {unit})")
        return redirect('watchman_dashboard')
    
    # Show last 10 visitors
    # Here we filter by society if unit or recorded_by helps identify the society
    # For now, we take all but in a real app we'd scope this by society_name
    past_visitors = Visitor.objects.all().order_by('-time_in')[:10]
    return render(request, 'core/watchman_dashboard.html', {'past_visitors': past_visitors})

@login_required
def gate_records(request):
    if request.user.role != 'watchman':
        return redirect('home')
    from admin_panel.models import Visitor
    all_visitors = Visitor.objects.all().order_by('-time_in')
    return render(request, 'core/gate_records.html', {'visitors': all_visitors})
