from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.template.loader import get_template
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from io import BytesIO
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, get_user_model
from django.urls import reverse
from django.db import IntegrityError
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from decimal import Decimal
from datetime import date, datetime
import re, os
from django.conf import settings
from django.utils import timezone
from django.db.models import Sum
from resident.models import Bill
from PIL import Image
import numpy as np

_OCR_READER = None

def get_ocr_reader():
    """Lazily initializes the OCR reader, ensuring models are stored in a writable directory for Vercel."""
    global _OCR_READER
    if _OCR_READER is None:
        try:
            import easyocr
            # Vercel only allows writing to /tmp
            model_dir = '/tmp/easyocr_models'
            if not os.path.exists(model_dir):
                os.makedirs(model_dir, exist_ok=True)
            
            # Initialize reader with specific model directory
            _OCR_READER = easyocr.Reader(['en'], gpu=False, model_storage_directory=model_dir)
        except Exception as e:
            # More descriptive error for debugging
            print(f"OCR Initialization Error: {str(e)}")
            return None
    return _OCR_READER

User = get_user_model()

@never_cache
@csrf_protect
def register(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        full_name = request.POST.get('full_name', '')
        password = request.POST.get('password')
        role = request.POST.get('role', 'resident')
        mobile = request.POST.get('mobile')
        unit_number = request.POST.get('unit_number', '')

        if role in ['secretary', 'resident']:
            invite_code = request.POST.get('invite_code')
            if not invite_code:
                messages.error(request, 'Invite code is required.')
                return render(request, 'core/register.html')

            from .models import InviteCode
            invite_obj = InviteCode.objects.filter(code=invite_code).first()
            if not invite_obj:
                messages.error(request, 'Invalid invite code.')
                return render(request, 'core/register.html')

            society = invite_obj.society_name

            if role == 'secretary':
                existing_secretary = User.objects.filter(role='secretary', society_name=society).exists()
                if existing_secretary:
                    messages.error(request, 'A secretary already exists for this society.')
                    return render(request, 'core/register.html')
        else:
            society = None

        try:
            user = User.objects.create_user(
                username=email,
                email=email,
                first_name=full_name,
                password=password,
                role=role,
                # All residents who register publicly are owners by default.
                # Rental profiles are created by owners from within their portal.
                resident_role='owner' if role == 'resident' else None,
                mobile_number=mobile,
                society_name=society,
                unit_number=unit_number,
            )
            return redirect(reverse('login') + '?registered=true')
        except IntegrityError:
            messages.error(request, 'An account with this email already exists.')
            return render(request, 'core/register.html')
    return render(request, 'core/register.html')

@login_required
def dashboard_redirect(request):
    if request.user.role == 'company':
        return redirect('company_dashboard')
    if request.user.role == 'admin' or request.user.role == 'secretary':
        return redirect('admin_dashboard')
    if request.user.role == 'watchman':
        return redirect('watchman_dashboard')
    return redirect('resident_dashboard')

@login_required
def placeholder_view(request, feature_name):
    if feature_name.lower() == "notices":
        return redirect('notices')
    return render(request, 'core/placeholder.html', {'feature_name': feature_name.capitalize()})

@login_required
def members_view(request):
    if request.user.role == 'company':
        # Get all invite codes generated by this company to list active societies
        from .models import InviteCode
        invite_codes = InviteCode.objects.filter(company=request.user)
        # Unique societies
        # Since each society gets 1 code, the invite_codes queryset IS the list of societies.
        return render(request, 'core/company_members.html', {'societies': invite_codes})
    
    else:
        # Residents and Secretaries see members of their own society
        society_name = request.user.society_name
        members = User.objects.filter(society_name=society_name).exclude(id=request.user.id)
        
        # Calculate pending amounts for each member
        from resident.models import Bill
        from decimal import Decimal
        from datetime import date
        today = date.today()
        
        for member in members:
            pending_bills = member.bills.filter(status='Pending')
            total = Decimal('0.00')
            for bill in pending_bills:
                # Dynamic late fee check (same as other views)
                if bill.due_date and today > bill.due_date:
                    if not bill.is_late_applied:
                        late_fee = bill.total_amount * Decimal('0.21')
                        bill.late_fee_amount = late_fee
                        bill.total_amount += late_fee
                        bill.is_late_applied = True
                        bill.save()
                total += bill.total_amount
            member.pending_amount = total
            member.pending_count = pending_bills.count()
        
        from .models import InviteCode
        invite_obj = InviteCode.objects.filter(society_name=society_name).first()
        invite_code = invite_obj.code if invite_obj else None
        
        return render(request, 'core/society_members.html', {
            'members': members, 
            'society_name': society_name,
            'invite_code': invite_code
        })

@login_required
def notices_view(request):
    from .models import Notice
    society_name = request.user.society_name
    notices = Notice.objects.filter(society_name=society_name).order_by('-created_at')
    return render(request, 'core/notices.html', {'notices': notices})

@login_required
def maintenance_view(request):
    from .models import InviteCode, PaymentProof, RentPaymentProof, SocietyMaintenanceSettings, RentalChargeSettings
    from django.utils import timezone
    import re
    from datetime import datetime

    is_rental = (request.user.role == 'resident' and request.user.resident_role == 'rental')
    society_name = request.user.society_name
    
    # ─── Context Data ───
    if is_rental:
        # Rental Context
        rental_charge = RentalChargeSettings.objects.filter(rental_user=request.user).first()
        target_fee = rental_charge.monthly_rent if rental_charge else Decimal('0.00')
        expected_acc = rental_charge.account_number[-4:] if rental_charge and rental_charge.account_number else None
        proofs = RentPaymentProof.objects.filter(rental_user=request.user).order_by('-created_at')
        settings_obj = rental_charge
    else:
        # Maintenance Context
        maintenance_settings = SocietyMaintenanceSettings.objects.filter(society_name=society_name).first()
        target_fee = request.user.get_maintenance_balance()
        expected_acc = maintenance_settings.expected_payee_account if maintenance_settings else None
        
        if request.user.role == 'secretary':
            proofs = PaymentProof.objects.filter(society_name=society_name).order_by('-created_at')
        else:
            proofs = PaymentProof.objects.filter(user=request.user).order_by('-created_at')
        settings_obj = maintenance_settings

    if request.method == 'POST' and request.FILES.get('proof_image'):
        proof_file = request.FILES.get('proof_image')
        
        if is_rental:
            proof = RentPaymentProof.objects.create(
                rental_user=request.user,
                owner=request.user.owner,
                proof_image=proof_file
            )
        else:
            proof = PaymentProof.objects.create(
                user=request.user,
                society_name=society_name,
                proof_image=proof_file
            )
        
        # --- AI Verification UI Logic (OCR) ---
        try:
            reader = get_ocr_reader()
            if not reader: raise Exception("OCR Reader Error")
            
            # Correctly open and read binary file from S3 or Local Storage
            proof.proof_image.open('rb')
            image_bytes = proof.proof_image.read()
            proof.proof_image.close()
            
            from PIL import Image
            import numpy as np
            
            img = Image.open(BytesIO(image_bytes)).convert('RGB')
            results = reader.readtext(np.array(img))
            extracted_text = " ".join([res[1] for res in results])
            
            # --- OCR NORMALIZATION ---
            # OCR often confuses 'O' or 'o' with '0' (zero) in account numbers/amounts
            extracted_text = re.sub(r'([0-9])O', r'\1 0', extracted_text)
            extracted_text = extracted_text.replace('OO', '00').replace('oo', '00')
            
            # 1. Date Extraction
            date_patterns = [r'(\d{1,2}[/-]\d{1,2}[/-]\d{2,4})', r'(\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{2,4})']
            found_date = None
            date_range = (0,0)
            for pattern in date_patterns:
                match = re.search(pattern, extracted_text, re.IGNORECASE)
                if match:
                    date_str = match.group(1); date_range = match.span()
                    for fmt in ("%d/%m/%Y", "%d-%m-%Y", "%Y-%m-%d", "%d/%m/%y", "%d-%m-%y", "%d %b %Y"):
                        try: found_date = datetime.strptime(date_str, fmt).date(); break
                        except: continue
                    if found_date: break

            # 2. Transaction ID
            # Regex to find 10-30 alphanumeric characters that contain at least one DIGIT
            # and are NOT the word "Successful", "Pending", etc.
            txn_pattern = r'(?:Ref|UTR|Txn|Transaction|ID)[:\s]*([A-Z0-9]{10,35})'
            txn_matches = re.findall(txn_pattern, extracted_text, re.IGNORECASE)
            
            txn_id = None
            if txn_matches:
                # Filter out human-words like "SUCCESSFUL"
                valid_ids = []
                for tid in txn_matches:
                    upper_tid = tid.upper()
                    # Skip common labels read as IDs
                    if upper_tid in ["SUCCESSFUL", "TRANSACTION", "PENDING"]: continue
                    # Most IDs must have at least one digit
                    if any(char.isdigit() for char in upper_tid):
                        valid_ids.append(tid)
                
                if valid_ids:
                    # Prefer UTR-like (typically longer) IDs
                    txn_id = max(valid_ids, key=len)
            
            txn_range = (0,0)
            if txn_id:
                proof.transaction_id = txn_id
                # For masking later, find where it is
                m_txn = re.search(re.escape(txn_id), extracted_text)
                if m_txn: txn_range = m_txn.span()

            # 3. Amount Extraction: GREEDY TARGET SEARCH
            amount_found = False
            target_val = float(target_fee)
            target_str = str(int(target_val)) if target_val == int(target_val) else f"{target_val:.2f}"
            
            # Normalization helps here too (e.g. 1.OO -> 1.00)
            normalized_text = extracted_text.replace(' . ', '.').replace('. ', '.').replace(' .', '.')
            if target_str in normalized_text or str(int(target_val)) in normalized_text:
                proof.extracted_amount = Decimal(str(target_val))
                amount_found = True
            
            # --- RE-ENGINEERED ROBUST SCANNER (ALWAYS RUNS) ---
            potential_amounts = []
            candidates_str = ""
            transcript_str = extracted_text[:200].replace('\n', ' ')
            
            # Greedy search: Includes common OCR misreads of the currency symbol
            it = re.finditer(r'([0-9,]+\.[0-9]{2}|[₹rsFt]+[\s\.]*[0-9,]+|[0-9]{1,10})', normalized_text, re.IGNORECASE)
            
            for m in it:
                try:
                    num_raw = m.group(1).replace('₹', '').replace('Rs', '').replace('rs', '').replace('F', '').replace('t', '').replace(',', '').strip('.')
                    if not num_raw: continue
                    val = float(num_raw)
                    if val == 0: continue
                    s_idx = m.start(); e_idx = m.end()
                    
                    # WIDE RADAR (50 chars) to catch distant keywords
                    ctx_near = normalized_text[max(0, s_idx-50):min(len(normalized_text), e_idx+50)].lower()
                    
                    # MANDATORY NOISE BANNERS
                    if ':' in ctx_near or 'am' in ctx_near or 'pm' in ctx_near: continue
                    months = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']
                    if any(mon in ctx_near for mon in months): continue
                    
                    # UI Context
                    has_symbol = any(s in m.group(1).lower() for s in ['₹', 'rs', 'f', 't'])
                    has_decimal = ('.' in m.group(1) and len(m.group(1).split('.')[-1]) == 2)
                    
                    # FILTER: Strictly skip metadata/years
                    if 2020 <= val <= 2030 or val > 1000000: continue
                    if any(k in ctx_near for k in ['@', '.com', 'okaxis', 'okicici', 'utr', 'ref']): 
                        if not has_symbol: continue # IDs are noise unless ₹ is present
                    
                    priority = 0
                    if has_symbol: priority += 100 
                    if has_decimal: priority += 50 
                    if s_idx < 350: priority += 40 
                    if any(w in ctx_near for w in ['paid', 'amount', 'total', 'credited', 'recived', 'received']): priority += 60
                    
                    # --- NAME PENALTY ---
                    name_noise = ['mr', 'ms', 'shri', 'smt', 'dr', 'shetty', 'recipient', 'sender', 'uday', 'shriraj']
                    if any(n in ctx_near for n in name_noise) and not has_symbol:
                        priority -= 250 # CRUSH names to the bottom

                    potential_amounts.append({'val': val, 'priority': priority})
                except: continue
            
            if potential_amounts:
                potential_amounts.sort(key=lambda x: x['priority'], reverse=True)
                candidates_str = ", ".join([f"₹{p['val']} (P:{p['priority']})" for p in potential_amounts[:5]])
                
                found_target = False
                for p_obj in potential_amounts:
                    if abs(p_obj['val'] - target_val) < 0.05:
                        proof.extracted_amount = Decimal(str(p_obj['val']))
                        amount_found = True; found_target = True; break
                
                if not found_target:
                    proof.extracted_amount = Decimal(str(potential_amounts[0]['val']))
                    amount_found = True

            # 4. Recipient Check (Account Digits)
            digit_found = None
            raw_text_normalized = extracted_text.replace('O', '0').replace('o', '0').replace(' ', '')
            
            # HIGHEST PRIORITY: If our expected 4 digits exist ANYWHERE (after normalization)
            if expected_acc:
                if str(expected_acc) in raw_text_normalized:
                    digit_found = str(expected_acc)

            # SECOND PRIORITY: Anchor search near "Credited to"
            if not digit_found:
                text_lower = extracted_text.lower()
                anchor_idx = text_lower.find("credited")
                if anchor_idx != -1:
                    after_anchor = extracted_text[anchor_idx:anchor_idx+120]
                    # Look for XXXXX + 4 chars (allow O)
                    m = re.search(r'[X*]+[\s]*([0-9Oo]{4})', after_anchor, re.IGNORECASE)
                    if m: digit_found = m.group(1).replace('O', '0').replace('o', '0')
                    else:
                        # Just any 4 digits near it
                        m2 = re.findall(r'([0-9]{4})', after_anchor)
                        for d in m2:
                            if not (2020 <= int(d) <= 2030): digit_found = d; break

            if digit_found:
                proof.extracted_account_digits = digit_found[-4:]
            
            # --- VERIFICATION ---
            is_valid = True; reason = ""
            today_date = date.today()
            debug_info = f" | CANDIDATES: {candidates_str} | RAW OCR: {transcript_str}" if potential_amounts else f" | RAW OCR: {transcript_str}"

            if proof.transaction_id:
                already_exists = (
                    PaymentProof.objects.filter(transaction_id=proof.transaction_id).exclude(id=proof.id).exists() or
                    RentPaymentProof.objects.filter(transaction_id=proof.transaction_id).exclude(id=proof.id).exists()
                )
                if already_exists:
                    is_valid = False; reason += "Duplicate Transaction ID detected. "
            
            if found_date:
                proof.extracted_date = found_date
                if found_date != today_date:
                    is_valid = False; reason += f"Date Mismatch (Detected: {found_date}, Today: {today_date}). "
            else:
                is_valid = False; reason += "Date not detected. "

            if expected_acc:
                if not proof.extracted_account_digits or str(proof.extracted_account_digits) != str(expected_acc):
                    is_valid = False; reason += f"Account Mismatch (Last 4: {proof.extracted_account_digits or 'None'}). "

            if not amount_found or not found_target:
                is_valid = False
                reason += f"Amount Mismatch.{debug_info}"

            if is_valid:
                proof.status = 'verified'
                messages.success(request, f"✅ Verified: Matches Today's Date, Account Number, and Amount (₹{proof.extracted_amount}).")
            else:
                proof.status = 'pending'
                messages.warning(request, f"⚠️ Verification failed: {reason}")
            
            proof.save()
            
        except Exception as e:
            messages.warning(request, f'Proof uploaded, but AI verification skipped. ({str(e)})')
            
        return redirect('maintenance')

    return render(request, 'core/maintenance.html', {
        'is_rental': is_rental,
        'proofs': proofs,
        'society_name': society_name,
        'settings': settings_obj,
        'target_fee': target_fee,
    })

@login_required
def verify_payment_proof(request, proof_id, action):
    """Allows a Secretary or Admin to manually approve or reject a payment proof."""
    if request.user.role not in ['secretary', 'admin']:
        messages.error(request, "Permission denied.")
        return redirect('maintenance')
        
    from .models import PaymentProof, RentPaymentProof
    # Check both models if needed, but maintenance is usually PaymentProof
    proof = PaymentProof.objects.filter(id=proof_id, society_name=request.user.society_name).first()
    
    if not proof:
        # Check rental proofs if it's a rental portal context
        proof = RentPaymentProof.objects.filter(id=proof_id, owner=request.user).first()
        
    if not proof:
        messages.error(request, "Proof not found.")
        return redirect('maintenance')
        
    if action == 'approve':
        proof.status = 'approved'
        messages.success(request, f"Proof #{proof.id} has been manually approved.")
    elif action == 'reject':
        proof.status = 'rejected'
        messages.warning(request, f"Proof #{proof.id} has been rejected.")
    else:
        messages.error(request, "Invalid action.")
        
    proof.save()
    return redirect('maintenance')

@login_required
def delete_payment_proof(request, proof_id):
    from .models import PaymentProof, RentPaymentProof
    is_rental = (request.user.role == 'resident' and request.user.resident_role == 'rental')
    
    if is_rental:
        proof = RentPaymentProof.objects.filter(id=proof_id, rental_user=request.user).first()
    else:
        proof = PaymentProof.objects.filter(id=proof_id).first()
    
    if not proof:
        messages.error(request, "Proof not found.")
        return redirect('maintenance')
    
    # Check permission: Only owner or secretary can delete
    # For rent: only tenant or their owner
    can_delete = False
    if is_rental and (proof.rental_user == request.user or proof.owner == request.user):
        can_delete = True
    elif not is_rental and (proof.user == request.user or request.user.role == 'secretary'):
        can_delete = True

    if can_delete:
        proof.delete()
        messages.success(request, "Payment proof deleted successfully.")
    else:
        messages.error(request, "You do not have permission to delete this proof.")
        
    return redirect('maintenance')


@login_required
def generate_proof_receipt_pdf(request, proof_id):
    from .models import PaymentProof

    proof = PaymentProof.objects.filter(id=proof_id, user=request.user).first()

    if not proof:
        messages.error(request, "Receipt not found.")
        return redirect('maintenance')

    if proof.status not in ['verified', 'approved']:
        messages.error(request, "Receipt is only available for verified payments.")
        return redirect('maintenance')

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []
    title_style = ParagraphStyle('title', parent=styles['Title'], fontSize=18,
                                  textColor=colors.HexColor('#1a1a2e'), spaceAfter=6)
    story.append(Paragraph('PAYMENT PROOF RECEIPT', title_style))
    story.append(HRFlowable(width='100%', thickness=1, color=colors.HexColor('#e0e0e0')))
    story.append(Spacer(1, 0.4*cm))
    data = [
        ['Proof ID', f'PR-{proof.id}'],
        ['Resident', proof.user.get_full_name() or proof.user.username],
        ['Society', proof.society_name or '—'],
        ['Date Submitted', str(proof.created_at.date())],
        ['Transaction ID', proof.transaction_id or '—'],
        ['Amount', f'Rs. {proof.extracted_amount}'],
        ['Status', proof.status.upper()],
    ]
    table = Table(data, colWidths=[6*cm, 10*cm])
    table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, colors.HexColor('#f9f9f9')]),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#e0e0e0')),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#e0e0e0')),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(table)
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph('This is a system-generated receipt.', ParagraphStyle(
        'footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey, alignment=TA_CENTER)))
    doc.build(story)
    pdf = buffer.getvalue()
    buffer.close()

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="receipt_proof_{proof.id}.pdf"'
    response.write(pdf)
    return response
@login_required
def generate_proof_receipt(request, proof_id):
    from .models import PaymentProof, RentPaymentProof
    is_rental = (request.user.role == 'resident' and request.user.resident_role == 'rental')

    if is_rental:
        proof = get_object_or_404(RentPaymentProof, id=proof_id, rental_user=request.user, status__in=['verified', 'approved'])
        user_for_receipt = proof.rental_user
    else:
        proof = get_object_or_404(PaymentProof, id=proof_id, user=request.user, status__in=['verified', 'approved'])
        user_for_receipt = proof.user

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []
    title_style = ParagraphStyle('title', parent=styles['Title'], fontSize=18,
                                  textColor=colors.HexColor('#1a1a2e'), spaceAfter=6)
    story.append(Paragraph('PAYMENT RECEIPT', title_style))
    story.append(Paragraph(f'Proof #{proof.id}', ParagraphStyle('sub', parent=styles['Normal'],
                                                                  fontSize=10, textColor=colors.grey, spaceAfter=12)))
    story.append(HRFlowable(width='100%', thickness=1, color=colors.HexColor('#e0e0e0')))
    story.append(Spacer(1, 0.4*cm))
    data = [
        ['Resident', user_for_receipt.get_full_name() or user_for_receipt.username],
        ['Society', user_for_receipt.society_name or '—'],
        ['Unit No.', user_for_receipt.unit_number or '—'],
        ['Month', proof.created_at.strftime('%B %Y')],
        ['Transaction ID', proof.transaction_id or 'SOCIETY_INTERNAL'],
        ['Amount Paid', f'Rs. {proof.extracted_amount}'],
        ['Status', 'Verified'],
        ['Date', str(proof.created_at.date())],
    ]
    table = Table(data, colWidths=[6*cm, 10*cm])
    table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, colors.HexColor('#f9f9f9')]),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#e0e0e0')),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#e0e0e0')),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(table)
    story.append(Spacer(1, 0.8*cm))
    story.append(HRFlowable(width='100%', thickness=1, color=colors.HexColor('#e0e0e0')))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph('This is a system-generated receipt.', ParagraphStyle(
        'footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey, alignment=TA_CENTER)))
    doc.build(story)
    pdf = buffer.getvalue()
    buffer.close()

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="receipt_{proof.id}.pdf"'
    response.write(pdf)
    return response

@login_required
def watchman_dashboard(request):
    if request.user.role != 'watchman':
        return redirect('home')
    
    from admin_panel.models import Visitor
    from django.contrib import messages
    
    if request.method == 'POST':
        name = request.POST.get('name')
        unit = request.POST.get('unit')
        vehicle_number = request.POST.get('vehicle_number')
        if vehicle_number:
            vehicle_number = vehicle_number.upper()
        visitor_photo = request.FILES.get('visitor_photo')
        vehicle_photo = request.FILES.get('vehicle_photo')
        watchman_name = request.POST.get('watchman_name', request.user.get_full_name() or request.user.username)
        
        Visitor.objects.create(
            name=name,
            unit=unit,
            vehicle_number=vehicle_number,
            visitor_photo=visitor_photo,
            vehicle_photo=vehicle_photo,
            recorded_by=watchman_name,
            status='Inside'
        )
        messages.success(request, f"Entry recorded for {name} (Unit {unit})")
        return redirect('watchman_dashboard')
    
    # Show last 10 visitors
    # Here we filter by society if unit or recorded_by helps identify the society
    # For now, we take all but in a real app we'd scope this by society_name
    past_visitors = Visitor.objects.all().order_by('-time_in')[:10]
    return render(request, 'core/watchman_dashboard.html', {'past_visitors': past_visitors})

@login_required
def gate_records(request):
    if request.user.role != 'watchman':
        return redirect('home')
    from admin_panel.models import Visitor
    all_visitors = Visitor.objects.all().order_by('-time_in')
    return render(request, 'core/gate_records.html', {'visitors': all_visitors})
